apiVersion: apps/v1
kind: Deployment
metadata:
  name: disbursement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disbursement
  template:
    metadata:
      labels:
        app: disbursement
    spec:
      containers:
      - name: disbursementrepo
        image:  pensionmanagementcr.azurecr.io/disbursementrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: processpensionsn

---
apiVersion: v1
kind: Service
metadata:
  name: disbursement
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: disbursement
